version: "3"

services:
  gowebserver:
    build: .
    container_name: imersaofsfc2_desafio1
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    ports:
      - "8000:8000"